services:
  watgbridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watgbridge
    volumes:
      - /portainer/AppData/watgbridge/config.yaml:/app/config.yaml # File to File
      - /portainer/AppData/watgbridge/sqlite.db:/app/sqlite.db     # File to File
      - /portainer/AppData/watgbridge/wawebstore.db:/app/wawebstore.db # File to File
    restart: unless-stopped
